spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/urule
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 13579admin
  jackson:
    default-property-inclusion: non_null

urule:
  repository:
    databasetype: postgresql
    datasourcename: datasource

server:
  port: 8787
