spring:
  datasource:
    url: jdbc:mysql://cdh:3306/urule?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: paohaijiao
    password: 13579admin
  jackson:
    default-property-inclusion: non_null

urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
